### ISSUE TITLE
During training, whether the labels of the unlabelled data is used for training?

### ISSUE THREAD

**Issue by JappyPing** [ermongroup/ssdkl#5]
Hi,

SSDKL is an excellent for semi-supervised learning. I want to apply this method to solve my problem. However, I have a question about the unlabelled data. 

In SSDKL, the labelled data was divided into training, validating, testing and unlabelled data. In my understanding, the label (target values) of the unlabelled section should not be fed into the training model. However, from the functions of "def _setup_nns(self):" and "def  _compute_embeddings(self, sess):", the label "self.y_unlabeled" is also an input for NN training. Since my data contains real unlabelled data without any labells, if so, it seems that I cannot adapt my data to the SSDKL method directly.

Did I understand right? 

Thanks for your help~

Best regards,

Jappy

**Comment by sangmichaelxie** [comment]
Hi,

The method does not use labels on the unlabeled data for training. We may
be using them just for logging some metrics, but they are not going into
the loss. You should be able to use it for your purposes!

**Comment by JappyPing** [comment]
> 

Thanks so much~
